language: node_js
node_js:
- 9

branches:
  only:
  - master

install:
- npm run build

script:
- echo "READY TO DEPLOY! :D"

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: sneaker-tracker
